# Generated by Django 3.0.6 on 2020-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_book_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
